# Generated by Django 5.0.6 on 2026-05-27 14:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('country', models.CharField(default='IN', max_length=2)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.organization')),
            ],
            options={
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('actor', models.CharField(default='demo.analyst@breatheesg.com', max_length=120)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('label', models.CharField(max_length=180)),
                ('status', models.CharField(default='processed', max_length=30)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='parsed', max_length=30)),
                ('error', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.sourcebatch')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=80)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=160)),
                ('description', models.CharField(max_length=240)),
                ('original_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('original_unit', models.CharField(max_length=40)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('normalized_unit', models.CharField(max_length=40)),
                ('emission_factor', models.DecimalField(decimal_places=6, max_digits=12)),
                ('kg_co2e', models.DecimalField(decimal_places=4, max_digits=14)),
                ('suspicious_flags', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='needs_review', max_length=30)),
                ('edited_from_source', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.facility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.organization')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ingestion.sourcebatch')),
                ('source_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='ingestion.sourcerecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
